// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/mtini/proto/EATRequestResponse.proto

package io.mtini.proto;

import com.google.protobuf.AbstractMessageLite;

public final class EATRequestResponseProtos {
  private EATRequestResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EATRequestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.mtini.proto.EATRequestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    EATRequestResponse.Request getRequest();
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    EATRequestResponse.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    EATRequestResponse.Response getResponse();
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    EATRequestResponse.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code io.mtini.proto.EATRequestResponse}
   */
  public  static final class EATRequestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.mtini.proto.EATRequestResponse)
      EATRequestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EATRequestResponse.newBuilder() to construct.
    private EATRequestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EATRequestResponse() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EATRequestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EATRequestResponse.class, Builder.class);
    }

    public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.mtini.proto.EATRequestResponse.Request)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string jsonRequest = 1;</code>
       */
      String getJsonRequest();
      /**
       * <code>string jsonRequest = 1;</code>
       */
      com.google.protobuf.ByteString
          getJsonRequestBytes();

      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      boolean hasEntries();
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      EstateAccountProtos.LedgerEntries getEntries();
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder();

      /**
       * <code>bytes data = 3;</code>
       */
      com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code io.mtini.proto.EATRequestResponse.Request}
     */
    public  static final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.mtini.proto.EATRequestResponse.Request)
        RequestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Request.newBuilder() to construct.
      private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Request() {
        jsonRequest_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Request(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                jsonRequest_ = s;
                break;
              }
              case 18: {
                EstateAccountProtos.LedgerEntries.Builder subBuilder = null;
                if (entries_ != null) {
                  subBuilder = entries_.toBuilder();
                }
                entries_ = input.readMessage(EstateAccountProtos.LedgerEntries.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entries_);
                  entries_ = subBuilder.buildPartial();
                }

                break;
              }
              case 26: {

                data_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      public static final int JSONREQUEST_FIELD_NUMBER = 1;
      private volatile Object jsonRequest_;
      /**
       * <code>string jsonRequest = 1;</code>
       */
      public String getJsonRequest() {
        Object ref = jsonRequest_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jsonRequest_ = s;
          return s;
        }
      }
      /**
       * <code>string jsonRequest = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonRequestBytes() {
        Object ref = jsonRequest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsonRequest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ENTRIES_FIELD_NUMBER = 2;
      private EstateAccountProtos.LedgerEntries entries_;
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public boolean hasEntries() {
        return entries_ != null;
      }
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public EstateAccountProtos.LedgerEntries getEntries() {
        return entries_ == null ? EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
      }
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder() {
        return getEntries();
      }

      public static final int DATA_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getJsonRequestBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonRequest_);
        }
        if (entries_ != null) {
          output.writeMessage(2, getEntries());
        }
        if (!data_.isEmpty()) {
          output.writeBytes(3, data_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getJsonRequestBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonRequest_);
        }
        if (entries_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getEntries());
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Request)) {
          return super.equals(obj);
        }
        Request other = (Request) obj;

        boolean result = true;
        result = result && getJsonRequest()
            .equals(other.getJsonRequest());
        result = result && (hasEntries() == other.hasEntries());
        if (hasEntries()) {
          result = result && getEntries()
              .equals(other.getEntries());
        }
        result = result && getData()
            .equals(other.getData());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + JSONREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getJsonRequest().hashCode();
        if (hasEntries()) {
          hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
          hash = (53 * hash) + getEntries().hashCode();
        }
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Request parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data.array());
      }
      public static Request parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data.array(), extensionRegistry);
      }
      public static Request parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Request parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Request parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Request parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Request parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Request parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Request parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Request parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Request parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Request parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.mtini.proto.EATRequestResponse.Request}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.mtini.proto.EATRequestResponse.Request)
          RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Request_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Request.class, Builder.class);
        }

        // Construct using io.mtini.proto.EATRequestResponseProtos.EATRequestResponse.Request.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          jsonRequest_ = "";

          if (entriesBuilder_ == null) {
            entries_ = null;
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }
          data_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor;
        }

        @Override
        public Request getDefaultInstanceForType() {
          return Request.getDefaultInstance();
        }

        @Override
        public Request build() {
          Request result = buildPartial();
          if (!result.isInitialized()) {
            throw Builder.newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Request buildPartial() {
          Request result = new Request(this);
          result.jsonRequest_ = jsonRequest_;
          if (entriesBuilder_ == null) {
            result.entries_ = entries_;
          } else {
            result.entries_ = entriesBuilder_.build();
          }
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Request) {
            return mergeFrom((Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Request other) {
          if (other == Request.getDefaultInstance()) return this;
          if (!other.getJsonRequest().isEmpty()) {
            jsonRequest_ = other.jsonRequest_;
            onChanged();
          }
          if (other.hasEntries()) {
            mergeEntries(other.getEntries());
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Request parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Request) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object jsonRequest_ = "";
        /**
         * <code>string jsonRequest = 1;</code>
         */
        public String getJsonRequest() {
          Object ref = jsonRequest_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            jsonRequest_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string jsonRequest = 1;</code>
         */
        public com.google.protobuf.ByteString
            getJsonRequestBytes() {
          Object ref = jsonRequest_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            jsonRequest_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string jsonRequest = 1;</code>
         */
        public Builder setJsonRequest(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          jsonRequest_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string jsonRequest = 1;</code>
         */
        public Builder clearJsonRequest() {
          
          jsonRequest_ = getDefaultInstance().getJsonRequest();
          onChanged();
          return this;
        }
        /**
         * <code>string jsonRequest = 1;</code>
         */
        public Builder setJsonRequestBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
          
          jsonRequest_ = value;
          onChanged();
          return this;
        }

        private EstateAccountProtos.LedgerEntries entries_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder> entriesBuilder_;
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public boolean hasEntries() {
          return entriesBuilder_ != null || entries_ != null;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntries getEntries() {
          if (entriesBuilder_ == null) {
            return entries_ == null ? EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
          } else {
            return entriesBuilder_.getMessage();
          }
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder setEntries(EstateAccountProtos.LedgerEntries value) {
          if (entriesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entries_ = value;
            onChanged();
          } else {
            entriesBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder setEntries(
            EstateAccountProtos.LedgerEntries.Builder builderForValue) {
          if (entriesBuilder_ == null) {
            entries_ = builderForValue.build();
            onChanged();
          } else {
            entriesBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder mergeEntries(EstateAccountProtos.LedgerEntries value) {
          if (entriesBuilder_ == null) {
            if (entries_ != null) {
              entries_ =
                EstateAccountProtos.LedgerEntries.newBuilder(entries_).mergeFrom(value).buildPartial();
            } else {
              entries_ = value;
            }
            onChanged();
          } else {
            entriesBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder clearEntries() {
          if (entriesBuilder_ == null) {
            entries_ = null;
            onChanged();
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntries.Builder getEntriesBuilder() {
          
          onChanged();
          return getEntriesFieldBuilder().getBuilder();
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder() {
          if (entriesBuilder_ != null) {
            return entriesBuilder_.getMessageOrBuilder();
          } else {
            return entries_ == null ?
                EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
          }
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder>
            getEntriesFieldBuilder() {
          if (entriesBuilder_ == null) {
            entriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder>(
                    getEntries(),
                    getParentForChildren(),
                    isClean());
            entries_ = null;
          }
          return entriesBuilder_;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes data = 3;</code>
         */
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>bytes data = 3;</code>
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes data = 3;</code>
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.mtini.proto.EATRequestResponse.Request)
      }

      // @@protoc_insertion_point(class_scope:io.mtini.proto.EATRequestResponse.Request)
      private static final Request DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Request();
      }

      public static Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Request>
          PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @Override
        public Request parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
      }

      @Override
      public Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.mtini.proto.EATRequestResponse.Response)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string jsonResponse = 1;</code>
       */
      String getJsonResponse();
      /**
       * <code>string jsonResponse = 1;</code>
       */
      com.google.protobuf.ByteString
          getJsonResponseBytes();

      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      boolean hasEntries();
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      EstateAccountProtos.LedgerEntries getEntries();
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder();

      /**
       * <code>bytes data = 3;</code>
       */
      com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code io.mtini.proto.EATRequestResponse.Response}
     */
    public  static final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.mtini.proto.EATRequestResponse.Response)
        ResponseOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Response.newBuilder() to construct.
      private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Response() {
        jsonResponse_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Response(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                jsonResponse_ = s;
                break;
              }
              case 18: {
                EstateAccountProtos.LedgerEntries.Builder subBuilder = null;
                if (entries_ != null) {
                  subBuilder = entries_.toBuilder();
                }
                entries_ = input.readMessage(EstateAccountProtos.LedgerEntries.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entries_);
                  entries_ = subBuilder.buildPartial();
                }

                break;
              }
              case 26: {

                data_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      public static final int JSONRESPONSE_FIELD_NUMBER = 1;
      private volatile Object jsonResponse_;
      /**
       * <code>string jsonResponse = 1;</code>
       */
      public String getJsonResponse() {
        Object ref = jsonResponse_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jsonResponse_ = s;
          return s;
        }
      }
      /**
       * <code>string jsonResponse = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonResponseBytes() {
        Object ref = jsonResponse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsonResponse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ENTRIES_FIELD_NUMBER = 2;
      private EstateAccountProtos.LedgerEntries entries_;
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public boolean hasEntries() {
        return entries_ != null;
      }
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public EstateAccountProtos.LedgerEntries getEntries() {
        return entries_ == null ? EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
      }
      /**
       * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
       */
      public EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder() {
        return getEntries();
      }

      public static final int DATA_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getJsonResponseBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonResponse_);
        }
        if (entries_ != null) {
          output.writeMessage(2, getEntries());
        }
        if (!data_.isEmpty()) {
          output.writeBytes(3, data_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getJsonResponseBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonResponse_);
        }
        if (entries_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getEntries());
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Response)) {
          return super.equals(obj);
        }
        Response other = (Response) obj;

        boolean result = true;
        result = result && getJsonResponse()
            .equals(other.getJsonResponse());
        result = result && (hasEntries() == other.hasEntries());
        if (hasEntries()) {
          result = result && getEntries()
              .equals(other.getEntries());
        }
        result = result && getData()
            .equals(other.getData());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + JSONRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getJsonResponse().hashCode();
        if (hasEntries()) {
          hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
          hash = (53 * hash) + getEntries().hashCode();
        }
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Response parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data.array());
      }
      public static Response parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data.array(), extensionRegistry);
      }
      public static Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.mtini.proto.EATRequestResponse.Response}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.mtini.proto.EATRequestResponse.Response)
          ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Response.class, Builder.class);
        }

        // Construct using io.mtini.proto.EATRequestResponseProtos.EATRequestResponse.Response.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          jsonResponse_ = "";

          if (entriesBuilder_ == null) {
            entries_ = null;
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }
          data_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor;
        }

        @Override
        public Response getDefaultInstanceForType() {
          return Response.getDefaultInstance();
        }

        @Override
        public Response build() {
          Response result = buildPartial();
          if (!result.isInitialized()) {
            throw Builder.newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Response buildPartial() {
          Response result = new Response(this);
          result.jsonResponse_ = jsonResponse_;
          if (entriesBuilder_ == null) {
            result.entries_ = entries_;
          } else {
            result.entries_ = entriesBuilder_.build();
          }
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Response) {
            return mergeFrom((Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Response other) {
          if (other == Response.getDefaultInstance()) return this;
          if (!other.getJsonResponse().isEmpty()) {
            jsonResponse_ = other.jsonResponse_;
            onChanged();
          }
          if (other.hasEntries()) {
            mergeEntries(other.getEntries());
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Response parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Response) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object jsonResponse_ = "";
        /**
         * <code>string jsonResponse = 1;</code>
         */
        public String getJsonResponse() {
          Object ref = jsonResponse_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            jsonResponse_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string jsonResponse = 1;</code>
         */
        public com.google.protobuf.ByteString
            getJsonResponseBytes() {
          Object ref = jsonResponse_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            jsonResponse_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string jsonResponse = 1;</code>
         */
        public Builder setJsonResponse(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          jsonResponse_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string jsonResponse = 1;</code>
         */
        public Builder clearJsonResponse() {
          
          jsonResponse_ = getDefaultInstance().getJsonResponse();
          onChanged();
          return this;
        }
        /**
         * <code>string jsonResponse = 1;</code>
         */
        public Builder setJsonResponseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
          
          jsonResponse_ = value;
          onChanged();
          return this;
        }

        private EstateAccountProtos.LedgerEntries entries_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder> entriesBuilder_;
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public boolean hasEntries() {
          return entriesBuilder_ != null || entries_ != null;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntries getEntries() {
          if (entriesBuilder_ == null) {
            return entries_ == null ? EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
          } else {
            return entriesBuilder_.getMessage();
          }
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder setEntries(EstateAccountProtos.LedgerEntries value) {
          if (entriesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entries_ = value;
            onChanged();
          } else {
            entriesBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder setEntries(
            EstateAccountProtos.LedgerEntries.Builder builderForValue) {
          if (entriesBuilder_ == null) {
            entries_ = builderForValue.build();
            onChanged();
          } else {
            entriesBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder mergeEntries(EstateAccountProtos.LedgerEntries value) {
          if (entriesBuilder_ == null) {
            if (entries_ != null) {
              entries_ =
                EstateAccountProtos.LedgerEntries.newBuilder(entries_).mergeFrom(value).buildPartial();
            } else {
              entries_ = value;
            }
            onChanged();
          } else {
            entriesBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public Builder clearEntries() {
          if (entriesBuilder_ == null) {
            entries_ = null;
            onChanged();
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntries.Builder getEntriesBuilder() {
          
          onChanged();
          return getEntriesFieldBuilder().getBuilder();
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        public EstateAccountProtos.LedgerEntriesOrBuilder getEntriesOrBuilder() {
          if (entriesBuilder_ != null) {
            return entriesBuilder_.getMessageOrBuilder();
          } else {
            return entries_ == null ?
                EstateAccountProtos.LedgerEntries.getDefaultInstance() : entries_;
          }
        }
        /**
         * <code>.io.mtini.proto.LedgerEntries entries = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder>
            getEntriesFieldBuilder() {
          if (entriesBuilder_ == null) {
            entriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                EstateAccountProtos.LedgerEntries, EstateAccountProtos.LedgerEntries.Builder, EstateAccountProtos.LedgerEntriesOrBuilder>(
                    getEntries(),
                    getParentForChildren(),
                    isClean());
            entries_ = null;
          }
          return entriesBuilder_;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes data = 3;</code>
         */
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>bytes data = 3;</code>
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes data = 3;</code>
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.mtini.proto.EATRequestResponse.Response)
      }

      // @@protoc_insertion_point(class_scope:io.mtini.proto.EATRequestResponse.Response)
      private static final Response DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Response();
      }

      public static Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Response>
          PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @Override
        public Response parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
      }

      @Override
      public Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private Request request_;
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    public Request getRequest() {
      return request_ == null ? Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
     */
    public RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private Response response_;
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    public Response getResponse() {
      return response_ == null ? Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
     */
    public ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(2, getResponse());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EATRequestResponse)) {
        return super.equals(obj);
      }
      EATRequestResponse other = (EATRequestResponse) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EATRequestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static EATRequestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static EATRequestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EATRequestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EATRequestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EATRequestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EATRequestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EATRequestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EATRequestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EATRequestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EATRequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EATRequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EATRequestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.mtini.proto.EATRequestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.mtini.proto.EATRequestResponse)
        EATRequestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EATRequestResponse.class, Builder.class);
      }

      // Construct using io.mtini.proto.EATRequestResponseProtos.EATRequestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EATRequestResponseProtos.internal_static_io_mtini_proto_EATRequestResponse_descriptor;
      }

      @Override
      public EATRequestResponse getDefaultInstanceForType() {
        return EATRequestResponse.getDefaultInstance();
      }

      @Override
      public EATRequestResponse build() {
        EATRequestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EATRequestResponse buildPartial() {
        EATRequestResponse result = new EATRequestResponse(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EATRequestResponse) {
          return mergeFrom((EATRequestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EATRequestResponse other) {
        if (other == EATRequestResponse.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EATRequestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EATRequestResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Request, Request.Builder, RequestOrBuilder> requestBuilder_;
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Builder setRequest(Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Builder setRequest(
          Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Builder mergeRequest(Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      public RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Request, Request.Builder, RequestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Request, Request.Builder, RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Response, Response.Builder, ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Builder setResponse(Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Builder setResponse(
          Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Builder mergeResponse(Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      public ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.io.mtini.proto.EATRequestResponse.Response response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Response, Response.Builder, ResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Response, Response.Builder, ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.mtini.proto.EATRequestResponse)
    }

    // @@protoc_insertion_point(class_scope:io.mtini.proto.EATRequestResponse)
    private static final EATRequestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EATRequestResponse();
    }

    public static EATRequestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EATRequestResponse>
        PARSER = new com.google.protobuf.AbstractParser<EATRequestResponse>() {
      @Override
      public EATRequestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EATRequestResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EATRequestResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EATRequestResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public EATRequestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_EATRequestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_EATRequestResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_EATRequestResponse_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_EATRequestResponse_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\'io/mtini/proto/EATRequestResponse.prot" +
      "o\022\016io.mtini.proto\032!io/mtini/proto/Estate" +
      "Ledger.proto\"\316\002\n\022EATRequestResponse\022;\n\007r" +
      "equest\030\001 \001(\0132*.io.mtini.proto.EATRequest" +
      "Response.Request\022=\n\010response\030\002 \001(\0132+.io." +
      "mtini.proto.EATRequestResponse.Response\032" +
      "\\\n\007Request\022\023\n\013jsonRequest\030\001 \001(\t\022.\n\007entri" +
      "es\030\002 \001(\0132\035.io.mtini.proto.LedgerEntries\022" +
      "\014\n\004data\030\003 \001(\014\032^\n\010Response\022\024\n\014jsonRespons" +
      "e\030\001 \001(\t\022.\n\007entries\030\002 \001(\0132\035.io.mtini.prot" +
      "o.LedgerEntries\022\014\n\004data\030\003 \001(\014B\032B\030EATRequ" +
      "estResponseProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          EstateAccountProtos.getDescriptor(),
        }, assigner);
    internal_static_io_mtini_proto_EATRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_mtini_proto_EATRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_EATRequestResponse_descriptor,
        new String[] { "Request", "Response", });
    internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor =
      internal_static_io_mtini_proto_EATRequestResponse_descriptor.getNestedTypes().get(0);
    internal_static_io_mtini_proto_EATRequestResponse_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_EATRequestResponse_Request_descriptor,
        new String[] { "JsonRequest", "Entries", "Data", });
    internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor =
      internal_static_io_mtini_proto_EATRequestResponse_descriptor.getNestedTypes().get(1);
    internal_static_io_mtini_proto_EATRequestResponse_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_EATRequestResponse_Response_descriptor,
        new String[] { "JsonResponse", "Entries", "Data", });
    EstateAccountProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
