// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/MtiniWallet.proto

package io.mtini.proto;

public final class MtiniWalletProtos {
  private MtiniWalletProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MtiniWalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.mtini.proto.MtiniWallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string privateKeyHex = 1;</code>
     * @return The privateKeyHex.
     */
    java.lang.String getPrivateKeyHex();
    /**
     * <code>string privateKeyHex = 1;</code>
     * @return The bytes for privateKeyHex.
     */
    com.google.protobuf.ByteString
        getPrivateKeyHexBytes();

    /**
     * <code>string initializationVectorHex = 2;</code>
     * @return The initializationVectorHex.
     */
    java.lang.String getInitializationVectorHex();
    /**
     * <code>string initializationVectorHex = 2;</code>
     * @return The bytes for initializationVectorHex.
     */
    com.google.protobuf.ByteString
        getInitializationVectorHexBytes();

    /**
     * <code>bool encrypted = 3;</code>
     * @return The encrypted.
     */
    boolean getEncrypted();

    /**
     * <code>string publicKeyHex = 4;</code>
     * @return The publicKeyHex.
     */
    java.lang.String getPublicKeyHex();
    /**
     * <code>string publicKeyHex = 4;</code>
     * @return The bytes for publicKeyHex.
     */
    com.google.protobuf.ByteString
        getPublicKeyHexBytes();

    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string id2 = 6;</code>
     * @return The id2.
     */
    java.lang.String getId2();
    /**
     * <code>string id2 = 6;</code>
     * @return The bytes for id2.
     */
    com.google.protobuf.ByteString
        getId2Bytes();

    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @return A list containing the transactionOutputs.
     */
    java.util.List<com.google.protobuf.ByteString> getTransactionOutputsList();
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @return The count of transactionOutputs.
     */
    int getTransactionOutputsCount();
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @param index The index of the element to return.
     * @return The transactionOutputs at the given index.
     */
    com.google.protobuf.ByteString getTransactionOutputs(int index);
  }
  /**
   * Protobuf type {@code io.mtini.proto.MtiniWallet}
   */
  public static final class MtiniWallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.mtini.proto.MtiniWallet)
      MtiniWalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtiniWallet.newBuilder() to construct.
    private MtiniWallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtiniWallet() {
      privateKeyHex_ = "";
      initializationVectorHex_ = "";
      publicKeyHex_ = "";
      id_ = "";
      id2_ = "";
      transactionOutputs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MtiniWallet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MtiniWallet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              privateKeyHex_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              initializationVectorHex_ = s;
              break;
            }
            case 24: {

              encrypted_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              publicKeyHex_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              id2_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                transactionOutputs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactionOutputs_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          transactionOutputs_ = java.util.Collections.unmodifiableList(transactionOutputs_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mtini.proto.MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mtini.proto.MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.mtini.proto.MtiniWalletProtos.MtiniWallet.class, io.mtini.proto.MtiniWalletProtos.MtiniWallet.Builder.class);
    }

    public static final int PRIVATEKEYHEX_FIELD_NUMBER = 1;
    private volatile java.lang.Object privateKeyHex_;
    /**
     * <code>string privateKeyHex = 1;</code>
     * @return The privateKeyHex.
     */
    @java.lang.Override
    public java.lang.String getPrivateKeyHex() {
      java.lang.Object ref = privateKeyHex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privateKeyHex_ = s;
        return s;
      }
    }
    /**
     * <code>string privateKeyHex = 1;</code>
     * @return The bytes for privateKeyHex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrivateKeyHexBytes() {
      java.lang.Object ref = privateKeyHex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        privateKeyHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIALIZATIONVECTORHEX_FIELD_NUMBER = 2;
    private volatile java.lang.Object initializationVectorHex_;
    /**
     * <code>string initializationVectorHex = 2;</code>
     * @return The initializationVectorHex.
     */
    @java.lang.Override
    public java.lang.String getInitializationVectorHex() {
      java.lang.Object ref = initializationVectorHex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initializationVectorHex_ = s;
        return s;
      }
    }
    /**
     * <code>string initializationVectorHex = 2;</code>
     * @return The bytes for initializationVectorHex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInitializationVectorHexBytes() {
      java.lang.Object ref = initializationVectorHex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initializationVectorHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTED_FIELD_NUMBER = 3;
    private boolean encrypted_;
    /**
     * <code>bool encrypted = 3;</code>
     * @return The encrypted.
     */
    @java.lang.Override
    public boolean getEncrypted() {
      return encrypted_;
    }

    public static final int PUBLICKEYHEX_FIELD_NUMBER = 4;
    private volatile java.lang.Object publicKeyHex_;
    /**
     * <code>string publicKeyHex = 4;</code>
     * @return The publicKeyHex.
     */
    @java.lang.Override
    public java.lang.String getPublicKeyHex() {
      java.lang.Object ref = publicKeyHex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicKeyHex_ = s;
        return s;
      }
    }
    /**
     * <code>string publicKeyHex = 4;</code>
     * @return The bytes for publicKeyHex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublicKeyHexBytes() {
      java.lang.Object ref = publicKeyHex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKeyHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID2_FIELD_NUMBER = 6;
    private volatile java.lang.Object id2_;
    /**
     * <code>string id2 = 6;</code>
     * @return The id2.
     */
    @java.lang.Override
    public java.lang.String getId2() {
      java.lang.Object ref = id2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id2_ = s;
        return s;
      }
    }
    /**
     * <code>string id2 = 6;</code>
     * @return The bytes for id2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getId2Bytes() {
      java.lang.Object ref = id2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONOUTPUTS_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> transactionOutputs_;
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @return A list containing the transactionOutputs.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getTransactionOutputsList() {
      return transactionOutputs_;
    }
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @return The count of transactionOutputs.
     */
    public int getTransactionOutputsCount() {
      return transactionOutputs_.size();
    }
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     * @param index The index of the element to return.
     * @return The transactionOutputs at the given index.
     */
    public com.google.protobuf.ByteString getTransactionOutputs(int index) {
      return transactionOutputs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPrivateKeyHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, privateKeyHex_);
      }
      if (!getInitializationVectorHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, initializationVectorHex_);
      }
      if (encrypted_ != false) {
        output.writeBool(3, encrypted_);
      }
      if (!getPublicKeyHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, publicKeyHex_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (!getId2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, id2_);
      }
      for (int i = 0; i < transactionOutputs_.size(); i++) {
        output.writeBytes(7, transactionOutputs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPrivateKeyHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, privateKeyHex_);
      }
      if (!getInitializationVectorHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, initializationVectorHex_);
      }
      if (encrypted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, encrypted_);
      }
      if (!getPublicKeyHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, publicKeyHex_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (!getId2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, id2_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < transactionOutputs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(transactionOutputs_.get(i));
        }
        size += dataSize;
        size += 1 * getTransactionOutputsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.mtini.proto.MtiniWalletProtos.MtiniWallet)) {
        return super.equals(obj);
      }
      io.mtini.proto.MtiniWalletProtos.MtiniWallet other = (io.mtini.proto.MtiniWalletProtos.MtiniWallet) obj;

      if (!getPrivateKeyHex()
          .equals(other.getPrivateKeyHex())) return false;
      if (!getInitializationVectorHex()
          .equals(other.getInitializationVectorHex())) return false;
      if (getEncrypted()
          != other.getEncrypted()) return false;
      if (!getPublicKeyHex()
          .equals(other.getPublicKeyHex())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getId2()
          .equals(other.getId2())) return false;
      if (!getTransactionOutputsList()
          .equals(other.getTransactionOutputsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRIVATEKEYHEX_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKeyHex().hashCode();
      hash = (37 * hash) + INITIALIZATIONVECTORHEX_FIELD_NUMBER;
      hash = (53 * hash) + getInitializationVectorHex().hashCode();
      hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEncrypted());
      hash = (37 * hash) + PUBLICKEYHEX_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKeyHex().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ID2_FIELD_NUMBER;
      hash = (53 * hash) + getId2().hashCode();
      if (getTransactionOutputsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONOUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.mtini.proto.MtiniWalletProtos.MtiniWallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.mtini.proto.MtiniWallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.mtini.proto.MtiniWallet)
        io.mtini.proto.MtiniWalletProtos.MtiniWalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mtini.proto.MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mtini.proto.MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.mtini.proto.MtiniWalletProtos.MtiniWallet.class, io.mtini.proto.MtiniWalletProtos.MtiniWallet.Builder.class);
      }

      // Construct using io.mtini.proto.MtiniWalletProtos.MtiniWallet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        privateKeyHex_ = "";

        initializationVectorHex_ = "";

        encrypted_ = false;

        publicKeyHex_ = "";

        id_ = "";

        id2_ = "";

        transactionOutputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mtini.proto.MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
      }

      @java.lang.Override
      public io.mtini.proto.MtiniWalletProtos.MtiniWallet getDefaultInstanceForType() {
        return io.mtini.proto.MtiniWalletProtos.MtiniWallet.getDefaultInstance();
      }

      @java.lang.Override
      public io.mtini.proto.MtiniWalletProtos.MtiniWallet build() {
        io.mtini.proto.MtiniWalletProtos.MtiniWallet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.mtini.proto.MtiniWalletProtos.MtiniWallet buildPartial() {
        io.mtini.proto.MtiniWalletProtos.MtiniWallet result = new io.mtini.proto.MtiniWalletProtos.MtiniWallet(this);
        int from_bitField0_ = bitField0_;
        result.privateKeyHex_ = privateKeyHex_;
        result.initializationVectorHex_ = initializationVectorHex_;
        result.encrypted_ = encrypted_;
        result.publicKeyHex_ = publicKeyHex_;
        result.id_ = id_;
        result.id2_ = id2_;
        if (((bitField0_ & 0x00000001) != 0)) {
          transactionOutputs_ = java.util.Collections.unmodifiableList(transactionOutputs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactionOutputs_ = transactionOutputs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mtini.proto.MtiniWalletProtos.MtiniWallet) {
          return mergeFrom((io.mtini.proto.MtiniWalletProtos.MtiniWallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.mtini.proto.MtiniWalletProtos.MtiniWallet other) {
        if (other == io.mtini.proto.MtiniWalletProtos.MtiniWallet.getDefaultInstance()) return this;
        if (!other.getPrivateKeyHex().isEmpty()) {
          privateKeyHex_ = other.privateKeyHex_;
          onChanged();
        }
        if (!other.getInitializationVectorHex().isEmpty()) {
          initializationVectorHex_ = other.initializationVectorHex_;
          onChanged();
        }
        if (other.getEncrypted() != false) {
          setEncrypted(other.getEncrypted());
        }
        if (!other.getPublicKeyHex().isEmpty()) {
          publicKeyHex_ = other.publicKeyHex_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getId2().isEmpty()) {
          id2_ = other.id2_;
          onChanged();
        }
        if (!other.transactionOutputs_.isEmpty()) {
          if (transactionOutputs_.isEmpty()) {
            transactionOutputs_ = other.transactionOutputs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionOutputsIsMutable();
            transactionOutputs_.addAll(other.transactionOutputs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.mtini.proto.MtiniWalletProtos.MtiniWallet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.mtini.proto.MtiniWalletProtos.MtiniWallet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object privateKeyHex_ = "";
      /**
       * <code>string privateKeyHex = 1;</code>
       * @return The privateKeyHex.
       */
      public java.lang.String getPrivateKeyHex() {
        java.lang.Object ref = privateKeyHex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          privateKeyHex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       * @return The bytes for privateKeyHex.
       */
      public com.google.protobuf.ByteString
          getPrivateKeyHexBytes() {
        java.lang.Object ref = privateKeyHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          privateKeyHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       * @param value The privateKeyHex to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKeyHex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKeyHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKeyHex() {
        
        privateKeyHex_ = getDefaultInstance().getPrivateKeyHex();
        onChanged();
        return this;
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       * @param value The bytes for privateKeyHex to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKeyHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        privateKeyHex_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object initializationVectorHex_ = "";
      /**
       * <code>string initializationVectorHex = 2;</code>
       * @return The initializationVectorHex.
       */
      public java.lang.String getInitializationVectorHex() {
        java.lang.Object ref = initializationVectorHex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          initializationVectorHex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       * @return The bytes for initializationVectorHex.
       */
      public com.google.protobuf.ByteString
          getInitializationVectorHexBytes() {
        java.lang.Object ref = initializationVectorHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          initializationVectorHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       * @param value The initializationVectorHex to set.
       * @return This builder for chaining.
       */
      public Builder setInitializationVectorHex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        initializationVectorHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitializationVectorHex() {
        
        initializationVectorHex_ = getDefaultInstance().getInitializationVectorHex();
        onChanged();
        return this;
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       * @param value The bytes for initializationVectorHex to set.
       * @return This builder for chaining.
       */
      public Builder setInitializationVectorHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        initializationVectorHex_ = value;
        onChanged();
        return this;
      }

      private boolean encrypted_ ;
      /**
       * <code>bool encrypted = 3;</code>
       * @return The encrypted.
       */
      @java.lang.Override
      public boolean getEncrypted() {
        return encrypted_;
      }
      /**
       * <code>bool encrypted = 3;</code>
       * @param value The encrypted to set.
       * @return This builder for chaining.
       */
      public Builder setEncrypted(boolean value) {
        
        encrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool encrypted = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncrypted() {
        
        encrypted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object publicKeyHex_ = "";
      /**
       * <code>string publicKeyHex = 4;</code>
       * @return The publicKeyHex.
       */
      public java.lang.String getPublicKeyHex() {
        java.lang.Object ref = publicKeyHex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publicKeyHex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       * @return The bytes for publicKeyHex.
       */
      public com.google.protobuf.ByteString
          getPublicKeyHexBytes() {
        java.lang.Object ref = publicKeyHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publicKeyHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       * @param value The publicKeyHex to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKeyHex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKeyHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKeyHex() {
        
        publicKeyHex_ = getDefaultInstance().getPublicKeyHex();
        onChanged();
        return this;
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       * @param value The bytes for publicKeyHex to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKeyHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publicKeyHex_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 5;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id2_ = "";
      /**
       * <code>string id2 = 6;</code>
       * @return The id2.
       */
      public java.lang.String getId2() {
        java.lang.Object ref = id2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id2 = 6;</code>
       * @return The bytes for id2.
       */
      public com.google.protobuf.ByteString
          getId2Bytes() {
        java.lang.Object ref = id2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id2 = 6;</code>
       * @param value The id2 to set.
       * @return This builder for chaining.
       */
      public Builder setId2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearId2() {
        
        id2_ = getDefaultInstance().getId2();
        onChanged();
        return this;
      }
      /**
       * <code>string id2 = 6;</code>
       * @param value The bytes for id2 to set.
       * @return This builder for chaining.
       */
      public Builder setId2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id2_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> transactionOutputs_ = java.util.Collections.emptyList();
      private void ensureTransactionOutputsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          transactionOutputs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(transactionOutputs_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @return A list containing the transactionOutputs.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTransactionOutputsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(transactionOutputs_) : transactionOutputs_;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @return The count of transactionOutputs.
       */
      public int getTransactionOutputsCount() {
        return transactionOutputs_.size();
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @param index The index of the element to return.
       * @return The transactionOutputs at the given index.
       */
      public com.google.protobuf.ByteString getTransactionOutputs(int index) {
        return transactionOutputs_.get(index);
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @param index The index to set the value at.
       * @param value The transactionOutputs to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionOutputs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionOutputsIsMutable();
        transactionOutputs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @param value The transactionOutputs to add.
       * @return This builder for chaining.
       */
      public Builder addTransactionOutputs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionOutputsIsMutable();
        transactionOutputs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @param values The transactionOutputs to add.
       * @return This builder for chaining.
       */
      public Builder addAllTransactionOutputs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTransactionOutputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionOutputs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionOutputs() {
        transactionOutputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.mtini.proto.MtiniWallet)
    }

    // @@protoc_insertion_point(class_scope:io.mtini.proto.MtiniWallet)
    private static final io.mtini.proto.MtiniWalletProtos.MtiniWallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.mtini.proto.MtiniWalletProtos.MtiniWallet();
    }

    public static io.mtini.proto.MtiniWalletProtos.MtiniWallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MtiniWallet>
        PARSER = new com.google.protobuf.AbstractParser<MtiniWallet>() {
      @java.lang.Override
      public MtiniWallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MtiniWallet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MtiniWallet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtiniWallet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.mtini.proto.MtiniWalletProtos.MtiniWallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_MtiniWallet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/MtiniWallet.proto\022\016io.mtini.prot" +
      "o\"\243\001\n\013MtiniWallet\022\025\n\rprivateKeyHex\030\001 \001(\t" +
      "\022\037\n\027initializationVectorHex\030\002 \001(\t\022\021\n\tenc" +
      "rypted\030\003 \001(\010\022\024\n\014publicKeyHex\030\004 \001(\t\022\n\n\002id" +
      "\030\005 \001(\t\022\013\n\003id2\030\006 \001(\t\022\032\n\022transactionOutput" +
      "s\030\007 \003(\014B\023B\021MtiniWalletProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_mtini_proto_MtiniWallet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_MtiniWallet_descriptor,
        new java.lang.String[] { "PrivateKeyHex", "InitializationVectorHex", "Encrypted", "PublicKeyHex", "Id", "Id2", "TransactionOutputs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
