// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/mtini/proto/MtiniWallet.proto

package io.mtini.proto;

import com.google.protobuf.AbstractMessageLite;

public final class MtiniWalletProtos {
  private MtiniWalletProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MtiniWalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.mtini.proto.MtiniWallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string privateKeyHex = 1;</code>
     */
    String getPrivateKeyHex();
    /**
     * <code>string privateKeyHex = 1;</code>
     */
    com.google.protobuf.ByteString
        getPrivateKeyHexBytes();

    /**
     * <code>string initializationVectorHex = 2;</code>
     */
    String getInitializationVectorHex();
    /**
     * <code>string initializationVectorHex = 2;</code>
     */
    com.google.protobuf.ByteString
        getInitializationVectorHexBytes();

    /**
     * <code>bool encrypted = 3;</code>
     */
    boolean getEncrypted();

    /**
     * <code>string publicKeyHex = 4;</code>
     */
    String getPublicKeyHex();
    /**
     * <code>string publicKeyHex = 4;</code>
     */
    com.google.protobuf.ByteString
        getPublicKeyHexBytes();

    /**
     * <code>string id = 5;</code>
     */
    String getId();
    /**
     * <code>string id = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string id2 = 6;</code>
     */
    String getId2();
    /**
     * <code>string id2 = 6;</code>
     */
    com.google.protobuf.ByteString
        getId2Bytes();

    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getTransactionOutputsList();
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    int getTransactionOutputsCount();
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    com.google.protobuf.ByteString getTransactionOutputs(int index);
  }
  /**
   * Protobuf type {@code io.mtini.proto.MtiniWallet}
   */
  public  static final class MtiniWallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.mtini.proto.MtiniWallet)
      MtiniWalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtiniWallet.newBuilder() to construct.
    private MtiniWallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtiniWallet() {
      privateKeyHex_ = "";
      initializationVectorHex_ = "";
      encrypted_ = false;
      publicKeyHex_ = "";
      id_ = "";
      id2_ = "";
      transactionOutputs_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MtiniWallet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              privateKeyHex_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              initializationVectorHex_ = s;
              break;
            }
            case 24: {

              encrypted_ = input.readBool();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              publicKeyHex_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              id2_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                transactionOutputs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000040;
              }
              transactionOutputs_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          transactionOutputs_ = java.util.Collections.unmodifiableList(transactionOutputs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MtiniWallet.class, Builder.class);
    }

    private int bitField0_;
    public static final int PRIVATEKEYHEX_FIELD_NUMBER = 1;
    private volatile Object privateKeyHex_;
    /**
     * <code>string privateKeyHex = 1;</code>
     */
    public String getPrivateKeyHex() {
      Object ref = privateKeyHex_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        privateKeyHex_ = s;
        return s;
      }
    }
    /**
     * <code>string privateKeyHex = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateKeyHexBytes() {
      Object ref = privateKeyHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        privateKeyHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIALIZATIONVECTORHEX_FIELD_NUMBER = 2;
    private volatile Object initializationVectorHex_;
    /**
     * <code>string initializationVectorHex = 2;</code>
     */
    public String getInitializationVectorHex() {
      Object ref = initializationVectorHex_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        initializationVectorHex_ = s;
        return s;
      }
    }
    /**
     * <code>string initializationVectorHex = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInitializationVectorHexBytes() {
      Object ref = initializationVectorHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        initializationVectorHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTED_FIELD_NUMBER = 3;
    private boolean encrypted_;
    /**
     * <code>bool encrypted = 3;</code>
     */
    public boolean getEncrypted() {
      return encrypted_;
    }

    public static final int PUBLICKEYHEX_FIELD_NUMBER = 4;
    private volatile Object publicKeyHex_;
    /**
     * <code>string publicKeyHex = 4;</code>
     */
    public String getPublicKeyHex() {
      Object ref = publicKeyHex_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        publicKeyHex_ = s;
        return s;
      }
    }
    /**
     * <code>string publicKeyHex = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPublicKeyHexBytes() {
      Object ref = publicKeyHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        publicKeyHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile Object id_;
    /**
     * <code>string id = 5;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID2_FIELD_NUMBER = 6;
    private volatile Object id2_;
    /**
     * <code>string id2 = 6;</code>
     */
    public String getId2() {
      Object ref = id2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id2_ = s;
        return s;
      }
    }
    /**
     * <code>string id2 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getId2Bytes() {
      Object ref = id2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONOUTPUTS_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> transactionOutputs_;
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTransactionOutputsList() {
      return transactionOutputs_;
    }
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    public int getTransactionOutputsCount() {
      return transactionOutputs_.size();
    }
    /**
     * <code>repeated bytes transactionOutputs = 7;</code>
     */
    public com.google.protobuf.ByteString getTransactionOutputs(int index) {
      return transactionOutputs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPrivateKeyHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, privateKeyHex_);
      }
      if (!getInitializationVectorHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, initializationVectorHex_);
      }
      if (encrypted_ != false) {
        output.writeBool(3, encrypted_);
      }
      if (!getPublicKeyHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, publicKeyHex_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (!getId2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, id2_);
      }
      for (int i = 0; i < transactionOutputs_.size(); i++) {
        output.writeBytes(7, transactionOutputs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPrivateKeyHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, privateKeyHex_);
      }
      if (!getInitializationVectorHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, initializationVectorHex_);
      }
      if (encrypted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, encrypted_);
      }
      if (!getPublicKeyHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, publicKeyHex_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (!getId2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, id2_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < transactionOutputs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(transactionOutputs_.get(i));
        }
        size += dataSize;
        size += 1 * getTransactionOutputsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MtiniWallet)) {
        return super.equals(obj);
      }
      MtiniWallet other = (MtiniWallet) obj;

      boolean result = true;
      result = result && getPrivateKeyHex()
          .equals(other.getPrivateKeyHex());
      result = result && getInitializationVectorHex()
          .equals(other.getInitializationVectorHex());
      result = result && (getEncrypted()
          == other.getEncrypted());
      result = result && getPublicKeyHex()
          .equals(other.getPublicKeyHex());
      result = result && getId()
          .equals(other.getId());
      result = result && getId2()
          .equals(other.getId2());
      result = result && getTransactionOutputsList()
          .equals(other.getTransactionOutputsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRIVATEKEYHEX_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKeyHex().hashCode();
      hash = (37 * hash) + INITIALIZATIONVECTORHEX_FIELD_NUMBER;
      hash = (53 * hash) + getInitializationVectorHex().hashCode();
      hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEncrypted());
      hash = (37 * hash) + PUBLICKEYHEX_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKeyHex().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ID2_FIELD_NUMBER;
      hash = (53 * hash) + getId2().hashCode();
      if (getTransactionOutputsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONOUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MtiniWallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static MtiniWallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static MtiniWallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MtiniWallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MtiniWallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MtiniWallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MtiniWallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MtiniWallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MtiniWallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MtiniWallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MtiniWallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MtiniWallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MtiniWallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.mtini.proto.MtiniWallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.mtini.proto.MtiniWallet)
        MtiniWalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MtiniWallet.class, Builder.class);
      }

      // Construct using io.mtini.proto.MtiniWalletProtos.MtiniWallet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        privateKeyHex_ = "";

        initializationVectorHex_ = "";

        encrypted_ = false;

        publicKeyHex_ = "";

        id_ = "";

        id2_ = "";

        transactionOutputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MtiniWalletProtos.internal_static_io_mtini_proto_MtiniWallet_descriptor;
      }

      @Override
      public MtiniWallet getDefaultInstanceForType() {
        return MtiniWallet.getDefaultInstance();
      }

      @Override
      public MtiniWallet build() {
        MtiniWallet result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MtiniWallet buildPartial() {
        MtiniWallet result = new MtiniWallet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.privateKeyHex_ = privateKeyHex_;
        result.initializationVectorHex_ = initializationVectorHex_;
        result.encrypted_ = encrypted_;
        result.publicKeyHex_ = publicKeyHex_;
        result.id_ = id_;
        result.id2_ = id2_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          transactionOutputs_ = java.util.Collections.unmodifiableList(transactionOutputs_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.transactionOutputs_ = transactionOutputs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MtiniWallet) {
          return mergeFrom((MtiniWallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MtiniWallet other) {
        if (other == MtiniWallet.getDefaultInstance()) return this;
        if (!other.getPrivateKeyHex().isEmpty()) {
          privateKeyHex_ = other.privateKeyHex_;
          onChanged();
        }
        if (!other.getInitializationVectorHex().isEmpty()) {
          initializationVectorHex_ = other.initializationVectorHex_;
          onChanged();
        }
        if (other.getEncrypted() != false) {
          setEncrypted(other.getEncrypted());
        }
        if (!other.getPublicKeyHex().isEmpty()) {
          publicKeyHex_ = other.publicKeyHex_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getId2().isEmpty()) {
          id2_ = other.id2_;
          onChanged();
        }
        if (!other.transactionOutputs_.isEmpty()) {
          if (transactionOutputs_.isEmpty()) {
            transactionOutputs_ = other.transactionOutputs_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureTransactionOutputsIsMutable();
            transactionOutputs_.addAll(other.transactionOutputs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MtiniWallet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MtiniWallet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object privateKeyHex_ = "";
      /**
       * <code>string privateKeyHex = 1;</code>
       */
      public String getPrivateKeyHex() {
        Object ref = privateKeyHex_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          privateKeyHex_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPrivateKeyHexBytes() {
        Object ref = privateKeyHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          privateKeyHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       */
      public Builder setPrivateKeyHex(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKeyHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       */
      public Builder clearPrivateKeyHex() {
        
        privateKeyHex_ = getDefaultInstance().getPrivateKeyHex();
        onChanged();
        return this;
      }
      /**
       * <code>string privateKeyHex = 1;</code>
       */
      public Builder setPrivateKeyHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
        
        privateKeyHex_ = value;
        onChanged();
        return this;
      }

      private Object initializationVectorHex_ = "";
      /**
       * <code>string initializationVectorHex = 2;</code>
       */
      public String getInitializationVectorHex() {
        Object ref = initializationVectorHex_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          initializationVectorHex_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInitializationVectorHexBytes() {
        Object ref = initializationVectorHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          initializationVectorHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       */
      public Builder setInitializationVectorHex(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        initializationVectorHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       */
      public Builder clearInitializationVectorHex() {
        
        initializationVectorHex_ = getDefaultInstance().getInitializationVectorHex();
        onChanged();
        return this;
      }
      /**
       * <code>string initializationVectorHex = 2;</code>
       */
      public Builder setInitializationVectorHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
        
        initializationVectorHex_ = value;
        onChanged();
        return this;
      }

      private boolean encrypted_ ;
      /**
       * <code>bool encrypted = 3;</code>
       */
      public boolean getEncrypted() {
        return encrypted_;
      }
      /**
       * <code>bool encrypted = 3;</code>
       */
      public Builder setEncrypted(boolean value) {
        
        encrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool encrypted = 3;</code>
       */
      public Builder clearEncrypted() {
        
        encrypted_ = false;
        onChanged();
        return this;
      }

      private Object publicKeyHex_ = "";
      /**
       * <code>string publicKeyHex = 4;</code>
       */
      public String getPublicKeyHex() {
        Object ref = publicKeyHex_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          publicKeyHex_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPublicKeyHexBytes() {
        Object ref = publicKeyHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          publicKeyHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       */
      public Builder setPublicKeyHex(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKeyHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       */
      public Builder clearPublicKeyHex() {
        
        publicKeyHex_ = getDefaultInstance().getPublicKeyHex();
        onChanged();
        return this;
      }
      /**
       * <code>string publicKeyHex = 4;</code>
       */
      public Builder setPublicKeyHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
        
        publicKeyHex_ = value;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 5;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object id2_ = "";
      /**
       * <code>string id2 = 6;</code>
       */
      public String getId2() {
        Object ref = id2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id2 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getId2Bytes() {
        Object ref = id2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id2 = 6;</code>
       */
      public Builder setId2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id2 = 6;</code>
       */
      public Builder clearId2() {
        
        id2_ = getDefaultInstance().getId2();
        onChanged();
        return this;
      }
      /**
       * <code>string id2 = 6;</code>
       */
      public Builder setId2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
        
        id2_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> transactionOutputs_ = java.util.Collections.emptyList();
      private void ensureTransactionOutputsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          transactionOutputs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(transactionOutputs_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTransactionOutputsList() {
        return java.util.Collections.unmodifiableList(transactionOutputs_);
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public int getTransactionOutputsCount() {
        return transactionOutputs_.size();
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public com.google.protobuf.ByteString getTransactionOutputs(int index) {
        return transactionOutputs_.get(index);
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public Builder setTransactionOutputs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionOutputsIsMutable();
        transactionOutputs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public Builder addTransactionOutputs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionOutputsIsMutable();
        transactionOutputs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public Builder addAllTransactionOutputs(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTransactionOutputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionOutputs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactionOutputs = 7;</code>
       */
      public Builder clearTransactionOutputs() {
        transactionOutputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.mtini.proto.MtiniWallet)
    }

    // @@protoc_insertion_point(class_scope:io.mtini.proto.MtiniWallet)
    private static final MtiniWallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MtiniWallet();
    }

    public static MtiniWallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MtiniWallet>
        PARSER = new com.google.protobuf.AbstractParser<MtiniWallet>() {
      @Override
      public MtiniWallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MtiniWallet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MtiniWallet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MtiniWallet> getParserForType() {
      return PARSER;
    }

    @Override
    public MtiniWallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_MtiniWallet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n io/mtini/proto/MtiniWallet.proto\022\016io.m" +
      "tini.proto\"\243\001\n\013MtiniWallet\022\025\n\rprivateKey" +
      "Hex\030\001 \001(\t\022\037\n\027initializationVectorHex\030\002 \001" +
      "(\t\022\021\n\tencrypted\030\003 \001(\010\022\024\n\014publicKeyHex\030\004 " +
      "\001(\t\022\n\n\002id\030\005 \001(\t\022\013\n\003id2\030\006 \001(\t\022\032\n\022transact" +
      "ionOutputs\030\007 \003(\014B\023B\021MtiniWalletProtosb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_mtini_proto_MtiniWallet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_mtini_proto_MtiniWallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_MtiniWallet_descriptor,
        new String[] { "PrivateKeyHex", "InitializationVectorHex", "Encrypted", "PublicKeyHex", "Id", "Id2", "TransactionOutputs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
