// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/RequestResponse.proto

package io.mtini.proto;

public final class RequestResponseProtos {
  private RequestResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.mtini.proto.RequestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     * @return The request.
     */
    io.mtini.proto.RequestResponseProtos.RequestResponse.Request getRequest();
    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     */
    io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     * @return The response.
     */
    io.mtini.proto.RequestResponseProtos.RequestResponse.Response getResponse();
    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     */
    io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code io.mtini.proto.RequestResponse}
   */
  public static final class RequestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.mtini.proto.RequestResponse)
      RequestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestResponse.newBuilder() to construct.
    private RequestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(io.mtini.proto.RequestResponseProtos.RequestResponse.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(io.mtini.proto.RequestResponseProtos.RequestResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.mtini.proto.RequestResponseProtos.RequestResponse.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Builder.class);
    }

    public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.mtini.proto.RequestResponse.Request)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string jsonRequest = 1;</code>
       * @return The jsonRequest.
       */
      java.lang.String getJsonRequest();
      /**
       * <code>string jsonRequest = 1;</code>
       * @return The bytes for jsonRequest.
       */
      com.google.protobuf.ByteString
          getJsonRequestBytes();

      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      com.google.protobuf.ByteString getData();

      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return Whether the entries field is set.
       */
      boolean hasEntries();
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return The entries.
       */
      com.google.protobuf.Any getEntries();
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       */
      com.google.protobuf.AnyOrBuilder getEntriesOrBuilder();
    }
    /**
     * Protobuf type {@code io.mtini.proto.RequestResponse.Request}
     */
    public static final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.mtini.proto.RequestResponse.Request)
        RequestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Request.newBuilder() to construct.
      private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Request() {
        jsonRequest_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Request();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Request(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                jsonRequest_ = s;
                break;
              }
              case 18: {

                data_ = input.readBytes();
                break;
              }
              case 26: {
                com.google.protobuf.Any.Builder subBuilder = null;
                if (entries_ != null) {
                  subBuilder = entries_.toBuilder();
                }
                entries_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entries_);
                  entries_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.mtini.proto.RequestResponseProtos.RequestResponse.Request.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder.class);
      }

      public static final int JSONREQUEST_FIELD_NUMBER = 1;
      private volatile java.lang.Object jsonRequest_;
      /**
       * <code>string jsonRequest = 1;</code>
       * @return The jsonRequest.
       */
      @java.lang.Override
      public java.lang.String getJsonRequest() {
        java.lang.Object ref = jsonRequest_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonRequest_ = s;
          return s;
        }
      }
      /**
       * <code>string jsonRequest = 1;</code>
       * @return The bytes for jsonRequest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getJsonRequestBytes() {
        java.lang.Object ref = jsonRequest_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonRequest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      public static final int ENTRIES_FIELD_NUMBER = 3;
      private com.google.protobuf.Any entries_;
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return Whether the entries field is set.
       */
      @java.lang.Override
      public boolean hasEntries() {
        return entries_ != null;
      }
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return The entries.
       */
      @java.lang.Override
      public com.google.protobuf.Any getEntries() {
        return entries_ == null ? com.google.protobuf.Any.getDefaultInstance() : entries_;
      }
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getEntriesOrBuilder() {
        return getEntries();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getJsonRequestBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonRequest_);
        }
        if (!data_.isEmpty()) {
          output.writeBytes(2, data_);
        }
        if (entries_ != null) {
          output.writeMessage(3, getEntries());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getJsonRequestBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonRequest_);
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, data_);
        }
        if (entries_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, getEntries());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.mtini.proto.RequestResponseProtos.RequestResponse.Request)) {
          return super.equals(obj);
        }
        io.mtini.proto.RequestResponseProtos.RequestResponse.Request other = (io.mtini.proto.RequestResponseProtos.RequestResponse.Request) obj;

        if (!getJsonRequest()
            .equals(other.getJsonRequest())) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (hasEntries() != other.hasEntries()) return false;
        if (hasEntries()) {
          if (!getEntries()
              .equals(other.getEntries())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + JSONREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getJsonRequest().hashCode();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        if (hasEntries()) {
          hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
          hash = (53 * hash) + getEntries().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.mtini.proto.RequestResponseProtos.RequestResponse.Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.mtini.proto.RequestResponse.Request}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.mtini.proto.RequestResponse.Request)
          io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Request_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Request_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.mtini.proto.RequestResponseProtos.RequestResponse.Request.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder.class);
        }

        // Construct using io.mtini.proto.RequestResponseProtos.RequestResponse.Request.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          jsonRequest_ = "";

          data_ = com.google.protobuf.ByteString.EMPTY;

          if (entriesBuilder_ == null) {
            entries_ = null;
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Request_descriptor;
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Request getDefaultInstanceForType() {
          return io.mtini.proto.RequestResponseProtos.RequestResponse.Request.getDefaultInstance();
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Request build() {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Request buildPartial() {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request result = new io.mtini.proto.RequestResponseProtos.RequestResponse.Request(this);
          result.jsonRequest_ = jsonRequest_;
          result.data_ = data_;
          if (entriesBuilder_ == null) {
            result.entries_ = entries_;
          } else {
            result.entries_ = entriesBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.mtini.proto.RequestResponseProtos.RequestResponse.Request) {
            return mergeFrom((io.mtini.proto.RequestResponseProtos.RequestResponse.Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.mtini.proto.RequestResponseProtos.RequestResponse.Request other) {
          if (other == io.mtini.proto.RequestResponseProtos.RequestResponse.Request.getDefaultInstance()) return this;
          if (!other.getJsonRequest().isEmpty()) {
            jsonRequest_ = other.jsonRequest_;
            onChanged();
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          if (other.hasEntries()) {
            mergeEntries(other.getEntries());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.mtini.proto.RequestResponseProtos.RequestResponse.Request) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object jsonRequest_ = "";
        /**
         * <code>string jsonRequest = 1;</code>
         * @return The jsonRequest.
         */
        public java.lang.String getJsonRequest() {
          java.lang.Object ref = jsonRequest_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            jsonRequest_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string jsonRequest = 1;</code>
         * @return The bytes for jsonRequest.
         */
        public com.google.protobuf.ByteString
            getJsonRequestBytes() {
          java.lang.Object ref = jsonRequest_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            jsonRequest_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string jsonRequest = 1;</code>
         * @param value The jsonRequest to set.
         * @return This builder for chaining.
         */
        public Builder setJsonRequest(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          jsonRequest_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string jsonRequest = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearJsonRequest() {
          
          jsonRequest_ = getDefaultInstance().getJsonRequest();
          onChanged();
          return this;
        }
        /**
         * <code>string jsonRequest = 1;</code>
         * @param value The bytes for jsonRequest to set.
         * @return This builder for chaining.
         */
        public Builder setJsonRequestBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          jsonRequest_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes data = 2;</code>
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>bytes data = 2;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes data = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }

        private com.google.protobuf.Any entries_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> entriesBuilder_;
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         * @return Whether the entries field is set.
         */
        public boolean hasEntries() {
          return entriesBuilder_ != null || entries_ != null;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         * @return The entries.
         */
        public com.google.protobuf.Any getEntries() {
          if (entriesBuilder_ == null) {
            return entries_ == null ? com.google.protobuf.Any.getDefaultInstance() : entries_;
          } else {
            return entriesBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder setEntries(com.google.protobuf.Any value) {
          if (entriesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entries_ = value;
            onChanged();
          } else {
            entriesBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder setEntries(
            com.google.protobuf.Any.Builder builderForValue) {
          if (entriesBuilder_ == null) {
            entries_ = builderForValue.build();
            onChanged();
          } else {
            entriesBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder mergeEntries(com.google.protobuf.Any value) {
          if (entriesBuilder_ == null) {
            if (entries_ != null) {
              entries_ =
                com.google.protobuf.Any.newBuilder(entries_).mergeFrom(value).buildPartial();
            } else {
              entries_ = value;
            }
            onChanged();
          } else {
            entriesBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder clearEntries() {
          if (entriesBuilder_ == null) {
            entries_ = null;
            onChanged();
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public com.google.protobuf.Any.Builder getEntriesBuilder() {
          
          onChanged();
          return getEntriesFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public com.google.protobuf.AnyOrBuilder getEntriesOrBuilder() {
          if (entriesBuilder_ != null) {
            return entriesBuilder_.getMessageOrBuilder();
          } else {
            return entries_ == null ?
                com.google.protobuf.Any.getDefaultInstance() : entries_;
          }
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
            getEntriesFieldBuilder() {
          if (entriesBuilder_ == null) {
            entriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                    getEntries(),
                    getParentForChildren(),
                    isClean());
            entries_ = null;
          }
          return entriesBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.mtini.proto.RequestResponse.Request)
      }

      // @@protoc_insertion_point(class_scope:io.mtini.proto.RequestResponse.Request)
      private static final io.mtini.proto.RequestResponseProtos.RequestResponse.Request DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.mtini.proto.RequestResponseProtos.RequestResponse.Request();
      }

      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Request>
          PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @java.lang.Override
        public Request parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.mtini.proto.RequestResponse.Response)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string jsonResponse = 1;</code>
       * @return The jsonResponse.
       */
      java.lang.String getJsonResponse();
      /**
       * <code>string jsonResponse = 1;</code>
       * @return The bytes for jsonResponse.
       */
      com.google.protobuf.ByteString
          getJsonResponseBytes();

      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      com.google.protobuf.ByteString getData();

      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return Whether the entries field is set.
       */
      boolean hasEntries();
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return The entries.
       */
      com.google.protobuf.Any getEntries();
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       */
      com.google.protobuf.AnyOrBuilder getEntriesOrBuilder();
    }
    /**
     * Protobuf type {@code io.mtini.proto.RequestResponse.Response}
     */
    public static final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.mtini.proto.RequestResponse.Response)
        ResponseOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Response.newBuilder() to construct.
      private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Response() {
        jsonResponse_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Response();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Response(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                jsonResponse_ = s;
                break;
              }
              case 18: {

                data_ = input.readBytes();
                break;
              }
              case 26: {
                com.google.protobuf.Any.Builder subBuilder = null;
                if (entries_ != null) {
                  subBuilder = entries_.toBuilder();
                }
                entries_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entries_);
                  entries_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.mtini.proto.RequestResponseProtos.RequestResponse.Response.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder.class);
      }

      public static final int JSONRESPONSE_FIELD_NUMBER = 1;
      private volatile java.lang.Object jsonResponse_;
      /**
       * <code>string jsonResponse = 1;</code>
       * @return The jsonResponse.
       */
      @java.lang.Override
      public java.lang.String getJsonResponse() {
        java.lang.Object ref = jsonResponse_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonResponse_ = s;
          return s;
        }
      }
      /**
       * <code>string jsonResponse = 1;</code>
       * @return The bytes for jsonResponse.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getJsonResponseBytes() {
        java.lang.Object ref = jsonResponse_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonResponse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      public static final int ENTRIES_FIELD_NUMBER = 3;
      private com.google.protobuf.Any entries_;
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return Whether the entries field is set.
       */
      @java.lang.Override
      public boolean hasEntries() {
        return entries_ != null;
      }
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       * @return The entries.
       */
      @java.lang.Override
      public com.google.protobuf.Any getEntries() {
        return entries_ == null ? com.google.protobuf.Any.getDefaultInstance() : entries_;
      }
      /**
       * <code>.google.protobuf.Any entries = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getEntriesOrBuilder() {
        return getEntries();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getJsonResponseBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonResponse_);
        }
        if (!data_.isEmpty()) {
          output.writeBytes(2, data_);
        }
        if (entries_ != null) {
          output.writeMessage(3, getEntries());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getJsonResponseBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonResponse_);
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, data_);
        }
        if (entries_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, getEntries());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.mtini.proto.RequestResponseProtos.RequestResponse.Response)) {
          return super.equals(obj);
        }
        io.mtini.proto.RequestResponseProtos.RequestResponse.Response other = (io.mtini.proto.RequestResponseProtos.RequestResponse.Response) obj;

        if (!getJsonResponse()
            .equals(other.getJsonResponse())) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (hasEntries() != other.hasEntries()) return false;
        if (hasEntries()) {
          if (!getEntries()
              .equals(other.getEntries())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + JSONRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getJsonResponse().hashCode();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        if (hasEntries()) {
          hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
          hash = (53 * hash) + getEntries().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.mtini.proto.RequestResponseProtos.RequestResponse.Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.mtini.proto.RequestResponse.Response}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.mtini.proto.RequestResponse.Response)
          io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.mtini.proto.RequestResponseProtos.RequestResponse.Response.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder.class);
        }

        // Construct using io.mtini.proto.RequestResponseProtos.RequestResponse.Response.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          jsonResponse_ = "";

          data_ = com.google.protobuf.ByteString.EMPTY;

          if (entriesBuilder_ == null) {
            entries_ = null;
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_Response_descriptor;
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Response getDefaultInstanceForType() {
          return io.mtini.proto.RequestResponseProtos.RequestResponse.Response.getDefaultInstance();
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Response build() {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.mtini.proto.RequestResponseProtos.RequestResponse.Response buildPartial() {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response result = new io.mtini.proto.RequestResponseProtos.RequestResponse.Response(this);
          result.jsonResponse_ = jsonResponse_;
          result.data_ = data_;
          if (entriesBuilder_ == null) {
            result.entries_ = entries_;
          } else {
            result.entries_ = entriesBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.mtini.proto.RequestResponseProtos.RequestResponse.Response) {
            return mergeFrom((io.mtini.proto.RequestResponseProtos.RequestResponse.Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.mtini.proto.RequestResponseProtos.RequestResponse.Response other) {
          if (other == io.mtini.proto.RequestResponseProtos.RequestResponse.Response.getDefaultInstance()) return this;
          if (!other.getJsonResponse().isEmpty()) {
            jsonResponse_ = other.jsonResponse_;
            onChanged();
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          if (other.hasEntries()) {
            mergeEntries(other.getEntries());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.mtini.proto.RequestResponseProtos.RequestResponse.Response) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object jsonResponse_ = "";
        /**
         * <code>string jsonResponse = 1;</code>
         * @return The jsonResponse.
         */
        public java.lang.String getJsonResponse() {
          java.lang.Object ref = jsonResponse_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            jsonResponse_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string jsonResponse = 1;</code>
         * @return The bytes for jsonResponse.
         */
        public com.google.protobuf.ByteString
            getJsonResponseBytes() {
          java.lang.Object ref = jsonResponse_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            jsonResponse_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string jsonResponse = 1;</code>
         * @param value The jsonResponse to set.
         * @return This builder for chaining.
         */
        public Builder setJsonResponse(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          jsonResponse_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string jsonResponse = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearJsonResponse() {
          
          jsonResponse_ = getDefaultInstance().getJsonResponse();
          onChanged();
          return this;
        }
        /**
         * <code>string jsonResponse = 1;</code>
         * @param value The bytes for jsonResponse to set.
         * @return This builder for chaining.
         */
        public Builder setJsonResponseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          jsonResponse_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes data = 2;</code>
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>bytes data = 2;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes data = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }

        private com.google.protobuf.Any entries_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> entriesBuilder_;
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         * @return Whether the entries field is set.
         */
        public boolean hasEntries() {
          return entriesBuilder_ != null || entries_ != null;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         * @return The entries.
         */
        public com.google.protobuf.Any getEntries() {
          if (entriesBuilder_ == null) {
            return entries_ == null ? com.google.protobuf.Any.getDefaultInstance() : entries_;
          } else {
            return entriesBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder setEntries(com.google.protobuf.Any value) {
          if (entriesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entries_ = value;
            onChanged();
          } else {
            entriesBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder setEntries(
            com.google.protobuf.Any.Builder builderForValue) {
          if (entriesBuilder_ == null) {
            entries_ = builderForValue.build();
            onChanged();
          } else {
            entriesBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder mergeEntries(com.google.protobuf.Any value) {
          if (entriesBuilder_ == null) {
            if (entries_ != null) {
              entries_ =
                com.google.protobuf.Any.newBuilder(entries_).mergeFrom(value).buildPartial();
            } else {
              entries_ = value;
            }
            onChanged();
          } else {
            entriesBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public Builder clearEntries() {
          if (entriesBuilder_ == null) {
            entries_ = null;
            onChanged();
          } else {
            entries_ = null;
            entriesBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public com.google.protobuf.Any.Builder getEntriesBuilder() {
          
          onChanged();
          return getEntriesFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        public com.google.protobuf.AnyOrBuilder getEntriesOrBuilder() {
          if (entriesBuilder_ != null) {
            return entriesBuilder_.getMessageOrBuilder();
          } else {
            return entries_ == null ?
                com.google.protobuf.Any.getDefaultInstance() : entries_;
          }
        }
        /**
         * <code>.google.protobuf.Any entries = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
            getEntriesFieldBuilder() {
          if (entriesBuilder_ == null) {
            entriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                    getEntries(),
                    getParentForChildren(),
                    isClean());
            entries_ = null;
          }
          return entriesBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.mtini.proto.RequestResponse.Response)
      }

      // @@protoc_insertion_point(class_scope:io.mtini.proto.RequestResponse.Response)
      private static final io.mtini.proto.RequestResponseProtos.RequestResponse.Response DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.mtini.proto.RequestResponseProtos.RequestResponse.Response();
      }

      public static io.mtini.proto.RequestResponseProtos.RequestResponse.Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Response>
          PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @java.lang.Override
        public Response parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private io.mtini.proto.RequestResponseProtos.RequestResponse.Request request_;
    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public io.mtini.proto.RequestResponseProtos.RequestResponse.Request getRequest() {
      return request_ == null ? io.mtini.proto.RequestResponseProtos.RequestResponse.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
     */
    @java.lang.Override
    public io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private io.mtini.proto.RequestResponseProtos.RequestResponse.Response response_;
    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public io.mtini.proto.RequestResponseProtos.RequestResponse.Response getResponse() {
      return response_ == null ? io.mtini.proto.RequestResponseProtos.RequestResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
     */
    @java.lang.Override
    public io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(2, getResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.mtini.proto.RequestResponseProtos.RequestResponse)) {
        return super.equals(obj);
      }
      io.mtini.proto.RequestResponseProtos.RequestResponse other = (io.mtini.proto.RequestResponseProtos.RequestResponse) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.mtini.proto.RequestResponseProtos.RequestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.mtini.proto.RequestResponseProtos.RequestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.mtini.proto.RequestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.mtini.proto.RequestResponse)
        io.mtini.proto.RequestResponseProtos.RequestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.mtini.proto.RequestResponseProtos.RequestResponse.class, io.mtini.proto.RequestResponseProtos.RequestResponse.Builder.class);
      }

      // Construct using io.mtini.proto.RequestResponseProtos.RequestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mtini.proto.RequestResponseProtos.internal_static_io_mtini_proto_RequestResponse_descriptor;
      }

      @java.lang.Override
      public io.mtini.proto.RequestResponseProtos.RequestResponse getDefaultInstanceForType() {
        return io.mtini.proto.RequestResponseProtos.RequestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.mtini.proto.RequestResponseProtos.RequestResponse build() {
        io.mtini.proto.RequestResponseProtos.RequestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.mtini.proto.RequestResponseProtos.RequestResponse buildPartial() {
        io.mtini.proto.RequestResponseProtos.RequestResponse result = new io.mtini.proto.RequestResponseProtos.RequestResponse(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mtini.proto.RequestResponseProtos.RequestResponse) {
          return mergeFrom((io.mtini.proto.RequestResponseProtos.RequestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.mtini.proto.RequestResponseProtos.RequestResponse other) {
        if (other == io.mtini.proto.RequestResponseProtos.RequestResponse.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.mtini.proto.RequestResponseProtos.RequestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.mtini.proto.RequestResponseProtos.RequestResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.mtini.proto.RequestResponseProtos.RequestResponse.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request, io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       * @return The request.
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? io.mtini.proto.RequestResponseProtos.RequestResponse.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public Builder setRequest(io.mtini.proto.RequestResponseProtos.RequestResponse.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public Builder setRequest(
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public Builder mergeRequest(io.mtini.proto.RequestResponseProtos.RequestResponse.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              io.mtini.proto.RequestResponseProtos.RequestResponse.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              io.mtini.proto.RequestResponseProtos.RequestResponse.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.mtini.proto.RequestResponseProtos.RequestResponse.Request, io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.mtini.proto.RequestResponseProtos.RequestResponse.Request, io.mtini.proto.RequestResponseProtos.RequestResponse.Request.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private io.mtini.proto.RequestResponseProtos.RequestResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response, io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       * @return The response.
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? io.mtini.proto.RequestResponseProtos.RequestResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public Builder setResponse(io.mtini.proto.RequestResponseProtos.RequestResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public Builder setResponse(
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public Builder mergeResponse(io.mtini.proto.RequestResponseProtos.RequestResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              io.mtini.proto.RequestResponseProtos.RequestResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      public io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              io.mtini.proto.RequestResponseProtos.RequestResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.io.mtini.proto.RequestResponse.Response response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.mtini.proto.RequestResponseProtos.RequestResponse.Response, io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.mtini.proto.RequestResponseProtos.RequestResponse.Response, io.mtini.proto.RequestResponseProtos.RequestResponse.Response.Builder, io.mtini.proto.RequestResponseProtos.RequestResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.mtini.proto.RequestResponse)
    }

    // @@protoc_insertion_point(class_scope:io.mtini.proto.RequestResponse)
    private static final io.mtini.proto.RequestResponseProtos.RequestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.mtini.proto.RequestResponseProtos.RequestResponse();
    }

    public static io.mtini.proto.RequestResponseProtos.RequestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestResponse>
        PARSER = new com.google.protobuf.AbstractParser<RequestResponse>() {
      @java.lang.Override
      public RequestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.mtini.proto.RequestResponseProtos.RequestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_RequestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_RequestResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_RequestResponse_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_RequestResponse_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mtini_proto_RequestResponse_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_mtini_proto_RequestResponse_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/RequestResponse.proto\022\016io.mtini." +
      "proto\032\031google/protobuf/any.proto\"\263\002\n\017Req" +
      "uestResponse\0228\n\007request\030\001 \001(\0132\'.io.mtini" +
      ".proto.RequestResponse.Request\022:\n\010respon" +
      "se\030\002 \001(\0132(.io.mtini.proto.RequestRespons" +
      "e.Response\032S\n\007Request\022\023\n\013jsonRequest\030\001 \001" +
      "(\t\022\014\n\004data\030\002 \001(\014\022%\n\007entries\030\003 \001(\0132\024.goog" +
      "le.protobuf.Any\032U\n\010Response\022\024\n\014jsonRespo" +
      "nse\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\022%\n\007entries\030\003 \001(\013" +
      "2\024.google.protobuf.AnyB\027B\025RequestRespons" +
      "eProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_io_mtini_proto_RequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_mtini_proto_RequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_RequestResponse_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_io_mtini_proto_RequestResponse_Request_descriptor =
      internal_static_io_mtini_proto_RequestResponse_descriptor.getNestedTypes().get(0);
    internal_static_io_mtini_proto_RequestResponse_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_RequestResponse_Request_descriptor,
        new java.lang.String[] { "JsonRequest", "Data", "Entries", });
    internal_static_io_mtini_proto_RequestResponse_Response_descriptor =
      internal_static_io_mtini_proto_RequestResponse_descriptor.getNestedTypes().get(1);
    internal_static_io_mtini_proto_RequestResponse_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_mtini_proto_RequestResponse_Response_descriptor,
        new java.lang.String[] { "JsonResponse", "Data", "Entries", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
